# Generated by Django 6.0.6 on 2026-06-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('cz_title', 'en_title'), name='unique_movie_titles'),
        ),
    ]
