# Generated by Django 6.0.6 on 2026-06-28 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_unique_movie_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titles', to='movies.country')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='movies.movie')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('movie', 'country', 'name'), name='unique_movie_title_per_country')],
            },
        ),
    ]
