# Generated by Django 6.0.6 on 2026-06-28 05:44

from django.db import migrations
from django.apps.registry import Apps

def transfer_titles_to_realtions(apps: Apps, schema_editor):
    Movie = apps.get_model("movies", "Movie")
    Title = apps.get_model("movies", "Title")
    Country = apps.get_model("movies", "Country")

    czechia, _ = Country.objects.get_or_create(name="Czechia")
    usa, _ = Country.objects.get_or_create(name="USA")

    for movie in Movie.objects.all():
        if movie.cz_title:
            Title.objects.get_or_create(
                movie=movie,
                country=czechia,
                name=movie.cz_title.strip()
            )
        
        if movie.en_title:
            Title.objects.get_or_create(
                movie=movie,
                country=usa,
                name=movie.en_title.strip()
            )

def reverse_titles_transfer(apps, schema_editor):
    Movie = apps.get_model('movies', 'Movie')
    Title = apps.get_model('movies', 'Title')

    for movie in Movie.objects.all():
        # Attempt to look up the relational data and map it back to the flat columns
        cz_title_obj = movie.titles.filter(country__name="Czechia").first()
        en_title_obj = movie.titles.filter(country__name="USA").first()

        if cz_title_obj:
            movie.cz_title = cz_title_obj.name
        if en_title_obj:
            movie.en_title = en_title_obj.name
        movie.save()

    # Clean up created title objects
    Title.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_country_titles'),
    ]

    operations = [
        migrations.RunPython(transfer_titles_to_realtions, reverse_code=reverse_titles_transfer)
    ]
