# Generated by Django 6.0.6 on 2026-06-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_migrate_movie_titles'),
    ]

    operations = [
        migrations.RemoveConstraint(
        model_name='movie',
        name='unique_movie_titles',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cz_title',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='en_title',
        ),

    ]
